### ISSUE TITLE
Getting NoneType in models.py

### ISSUE THREAD

**Issue by raghusumanth** [aiff22/DPED#26]
2020-03-13 00:28:09.773043: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-03-13 00:28:09.786026: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-13 00:28:09.794261: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]
WARNING:tensorflow:From C:\Python3\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "train_model.py", line 57, in <module>
    enhanced = models.resnet(phone_image)
  File "C:\Users\rkarnat\Python\DPED-master\DPED-master\models.py", line 13, in resnet
    c2 = tf.nn.relu(_instance_norm(conv2d(c1, W2) + b2))
  File "C:\Users\rkarnat\Python\DPED-master\DPED-master\models.py", line 114, in _instance_norm
    batch, rows, cols, channels = [i.value for i in net.get_shape()]
  File "C:\Users\rkarnat\Python\DPED-master\DPED-master\models.py", line 114, in <listcomp>
    batch, rows, cols, channels = [i.value for i in net.get_shape()]
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by aiff22** [comment]
If you are using TensorFlow 2+, please add the following code after importing tf library:

```bash
tf.compat.v1.disable_v2_behavior()
```

**Comment by raghusumanth** [comment]
Thank you. above issue is  resolved.

step6. Test the obtained models. 
 this step giving below output.

2020-03-13 09:01:44.545328: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-03-13 09:01:44.580901: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From C:\Python3\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From C:\Python3\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2020-03-13 09:01:53.883610: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-03-13 09:01:53.982217: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-03-13 09:01:54.638572: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-13 09:01:54.677279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]
Traceback (most recent call last):
  File "test_model.py", line 81, in <module>
    saver.restore(sess, "models/" + phone + "_iteration_" + str(i) + ".ckpt")
  File "C:\Python3\lib\site-packages\tensorflow_core\python\training\saver.py", line 1282, in restore
    checkpoint_prefix)
ValueError: The passed save_path is not a valid checkpoint: models/iphone_iteration_13000.ckpt


can you tell us why we are getting this.

**Comment by aiff22** [comment]
Hi @raghusumanth,

The code was updated to be compatible with TensorFlow 2.x.
